# Generated by Django 3.0 on 2021-12-19 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20211217_2316'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='fecha_nac',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='cant_publ',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='cantidad_coment',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='rol',
            name='descripcion_rol',
            field=models.TextField(blank=True, null=True),
        ),
    ]
