# Generated by Django 3.0 on 2021-12-20 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20211219_2057'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='descripcion_corta',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
    ]
