# Generated by Django 3.0 on 2021-12-20 04:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20211219_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacion',
            name='estado',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='blog.Estado'),
        ),
    ]
