# Generated by Django 3.0 on 2021-12-20 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20211220_0140'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacion',
            name='es_publico',
            field=models.BooleanField(default=True),
        ),
    ]
