# Generated by Django 3.0 on 2021-12-20 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_publicacion_es_publico'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='imagen',
            field=models.ImageField(default='default_user_profile.png', upload_to='images'),
        ),
    ]
