# Generated by Django 3.0 on 2021-12-24 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20211223_0149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='imagen',
            field=models.ImageField(default='default_user_profile.png', null=True, upload_to='images'),
        ),
    ]
