# Generated by Django 3.0 on 2021-12-24 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20211223_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='imagen',
            field=models.ImageField(blank=True, default='images/default_user_profile.png', null=True, upload_to='images'),
        ),
    ]
