# Generated by Django 3.0 on 2021-12-24 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_auto_20211224_0106'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacion',
            name='slug',
            field=models.SlugField(default='fix-me'),
            preserve_default=False,
        ),
    ]
